### ISSUE TITLE
Getting Code With Git

### ISSUE THREAD

**Issue by iamroshel** [learn-co-curriculum/phase-0-getting-code-with-git#4]
Navigation to the REACT REPO

- I don't have that SSH tab

**Comment by lizbur10** [comment]
Hi there!

Thanks for raising this issue. Based on your description, it sounds like the
issue may be related to your environment setup rather than with the lesson
itself or the instructions. The curriculum team monitors these issues so that we
can fix typos and bugs in the curriculum, but we aren't equipped to provide
support.

To get help with your question, you should either:

- Reach out to your instructor (if you've started the program and have an
  instructor)
- Use the
  [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit)
  feature in Canvas to connect with a Technical Coach on the Academic Success
  Team

Hope you are able to get this resolved!
